apiVersion: apps/v1

kind: Deployment

metadata:

   name: reuters-transformer


spec:

 replicas:2


 selector:

   matchLabels:

      app:reuters


 template:

   metadata:

      labels:

        app:reuters


   spec:

      containers:

      - name: reuters

        image:reuters

        ports:

        - containerPort:5000

---

apiVersion: v1

kind: Service

metadata:

 name: reuters-service


spec:

 selector:

   app:reuters


 ports:

 - protocol: TCP

   port:80

   targetPort:5000


 type: LoadBalancer
